import Footer from './components/footer/Footer'
import Menu from './components/menu/Menu'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Menu></Menu>
        </header>
        <div className='min-h-screen'>
          {children}
        </div>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  )
}
