import Footer from './components/footer/Footer'
import Header from './components/header/Header'
import './globals.css'
import { Saira } from 'next/font/google'

const saira = Saira({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900']})

export const metadata = {
  title: 'Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={saira.className}>
        <header>
          <Header></Header>
        </header>
        <div className='min-h-screen'>
          {children}
        </div>
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
  )
}
